replicaCount: 1

resources:
  limits:
    memory: 1Gi
    cpu: 1
  requests:
    memory: 512Mi
    cpu: 100m

env:
  # create me


psvc:
  name: Импорт фидов
  description: Воркер Импорта и Дедубликации Фидов
  istioSidecarSettings:
    limits:
      memory: 200Mi
      cpu: 200m
    requests:
      memory: 50Mi
      cpu: 10m
  roleMapping:
    - endpoint: /api/v1/todo-lists
      roles: admin
      methods: GET,POST
      zones: external
  publishAPI: true

spec:
  ports:
    - name: kafka
      port: 9092
      protocol: TCP
      targetPort: 9092

  livenessProbe:
    failureThreshold: 5
    httpGet:
      path: 0.0.0.0:8080/api/health/liveness
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 1

  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: 0.0.0.0:8080/api/health/health/readiness
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 1

vaultSecretKeys:
  - POSTGRES_PASSWORD
  - POSTGRES_USER

strategyType: Recreate

databases:
  - id: DATABASE_1
    type: POSTGRESQL
    host: 10.7.77.7
    port: 5432
    name: mydb

kafkaClusters:
  cluster-1:
    topics:
      syslog:
