replicaCount: 1

resources:
  limits:
    memory: 1Gi
    cpu: 1
  requests:
    memory: 512Mi
    cpu: 100m

env:
  # create me


psvc:
  name: # change me
  description: # change me
  istioSidecarSettings:
    limits:
      memory: 200Mi
      cpu: 200m
    requests:
      memory: 50Mi
      cpu: 10m
  roleMapping:
    - endpoint: /api/v1/todo-lists
      roles: admin
      methods: GET,POST
      zones: external
  publishAPI: true

vaultSecretKeys:
  - POSTGRES_PASSWORD
  - POSTGRES_USER

strategyType: Recreate

databases:
  - id: DATABASE_1
    type: POSTGRESQL
    host: 10.7.77.7
    port: 5432
    name: mydb

kafkaClusters:
  cluster-1:
    topics:
      syslog:
