# Generated by Django 4.0.4 on 2022-07-11 08:28

import django.core.validators
from django.db import migrations, models
import intelhandler.models


class Migration(migrations.Migration):

    dependencies = [
        ('intelhandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', intelhandler.models.CreationDateTimeField(auto_now_add=True, verbose_name='создано')),
                ('modified', intelhandler.models.ModificationDateTimeField(auto_now=True, verbose_name='изменено')),
            ],
            options={
                'verbose_name': 'Правило парсинга',
                'verbose_name_plural': 'Правила парсинга',
            },
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='FileHash',
        ),
        migrations.DeleteModel(
            name='FullURL',
        ),
        migrations.DeleteModel(
            name='IPAddress',
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': 'Индикатор', 'verbose_name_plural': 'Индикаторы'},
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='feed',
            name='custom_field',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Кастомное поле'),
        ),
        migrations.AddField(
            model_name='feed',
            name='indicators',
            field=models.ManyToManyField(blank=True, related_name='feeds', to='intelhandler.indicator', verbose_name='Индикатор'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='category',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Категория индикатора'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_affected_products_product',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_av_verdict',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_exploits_md5',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_exploits_sha1',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_exploits_sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_exploits_threat',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_file_names',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_file_size',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_file_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_files_behaviour',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_files_md5',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_files_sha1',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_files_sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_files_threat',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_geo',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_industry',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_ip',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_ip_geo',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_ip_whois_asn',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_ip_whois_contact_abuse_country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_ip_whois_contact_abuse_email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_ip_whois_contact_abuse_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_ip_whois_contact_owner_city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_ip_whois_contact_owner_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_ip_whois_contact_owner_country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_ip_whois_contact_owner_email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_ip_whois_contact_owner_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_ip_whois_country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_ip_whois_created',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_ip_whois_desrc',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_ip_whois_net_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_ip_whois_net_range',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_ip_whois_updated',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_malware',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_mask',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_md5',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_popularity',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_port',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_protocol',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_publication_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_severity',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_sha1',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_url',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_urls_url',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_vendors_vendor',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_whois_city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_whois_country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_whois_created',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_whois_domain',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_whois_email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_whois_expires',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_whois_mx',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_whois_mx_ips',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_whois_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_whois_ns',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_whois_ns_ips',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_whois_org',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_whois_registrar_email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_whois_registrar_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ioc_context_whois_updated',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='joc_context_domains',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='supplier_confidence',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Достоверность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicator',
            name='supplier_created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='supplier_name',
            field=models.CharField(default='', max_length=128, verbose_name='Название источника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicator',
            name='supplier_type',
            field=models.CharField(default='', max_length=64, verbose_name='Тип поставщика'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicator',
            name='supplier_vendor_name',
            field=models.CharField(default='', max_length=128, verbose_name='Название поставщика '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicator',
            name='tag',
            field=models.ManyToManyField(related_name='Теги', to='intelhandler.tag'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='uuid',
            field=models.CharField(default='', max_length=36, unique=True, verbose_name='Уникальный идентификатор индикатора'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MispEvent',
        ),
        migrations.DeleteModel(
            name='OrganizationContact',
        ),
        migrations.AddField(
            model_name='feed',
            name='parsing_rules',
            field=models.ManyToManyField(blank=True, related_name='feed_parsing_rules', to='intelhandler.parsingrule', verbose_name='Правила для парсинга'),
        ),
    ]
