# Generated by Django 4.0.4 on 2022-07-19 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intelhandler', '0002_parsingrule_delete_attribute_delete_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='ts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
