# Generated by Django 4.0.4 on 2022-08-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelhandler', '0003_feed_ts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('extra_data', models.JSONField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.AddField(
            model_name='feed',
            name='load_status',
            field=models.CharField(choices=[('NOT STARTED', 'Не началось'), ('ERROR', 'Ошибка'), ('DONE', 'Готово')], default='NOT STARTED', max_length=15),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ttl',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
    ]
