# Generated by Django 4.0.4 on 2022-08-03 07:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import intelhandler.models


class Migration(migrations.Migration):

    dependencies = [
        ('intelhandler', '0004_settingmodule_feed_load_status_indicator_ttl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', intelhandler.models.CreationDateTimeField(auto_now_add=True, verbose_name='создано')),
                ('modified', intelhandler.models.ModificationDateTimeField(auto_now=True, verbose_name='изменено')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_instead_full', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('provider_name', models.CharField(max_length=255)),
                ('path', models.TextField()),
                ('certificate', models.FileField(blank=True, null=True, upload_to='', verbose_name='Путь к сертификату')),
                ('authenticity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Достоверность')),
                ('format', models.CharField(choices=[('STIX', 'stix'), ('MISP', 'misp'), ('FREE_TEXT', 'free_text'), ('JSON', 'json'), ('CSV', 'csv')], default='CSV', max_length=15, verbose_name='Формат')),
                ('auth_type', models.CharField(choices=[('NAU', 'Отсуствует'), ('API', 'API token'), ('BSC', 'HTTP basic')], default='NAU', max_length=3, verbose_name='Тип авторизации')),
                ('auth_login', models.CharField(blank=True, max_length=32, null=True, verbose_name='Логин для авторизации')),
                ('auth_password', models.CharField(blank=True, max_length=64, null=True, verbose_name='Пароль для авторизации')),
                ('max_rows', models.IntegerField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
        migrations.DeleteModel(
            name='SettingModule',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='load_status',
        ),
        migrations.AddField(
            model_name='feed',
            name='update_status',
            field=models.CharField(choices=[('ENABLED', 'ENABLED'), ('DISABLED', 'DISABLED'), ('UPDATE_ERROR', 'UPDATE_ERROR')], default='ENABLED', max_length=15),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='ttl',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='feed',
            name='source',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intelhandler.source'),
        ),
    ]
