# Generated by Django 4.0.4 on 2022-08-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelhandler', '0005_source_delete_settingmodule_remove_feed_load_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='raw_indicators',
            field=models.TextField(default=None, null=True),
        ),
    ]
