# Generated by Django 4.0.4 on 2022-08-03 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelhandler', '0006_source_raw_indicators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='link',
            field=models.CharField(max_length=255, verbose_name='Ссылка на фид'),
        ),
        migrations.AlterField(
            model_name='source',
            name='authenticity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Достоверность'),
        ),
    ]
