# Generated by Django 4.0.4 on 2022-08-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelhandler', '0007_alter_feed_link_alter_source_authenticity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='format_of_feed',
            field=models.CharField(choices=[('CSV', 'CSV формат'), ('JSN', 'JSON формат'), ('XML', 'XML формат'), ('TXT', 'TXT формат')], default='TXT', max_length=15, verbose_name='Формат фида'),
        ),
    ]
