# Generated by Django 4.0.4 on 2022-08-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelhandler', '0009_alter_indicator_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='update_time_period',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
