sensors:
  use_threads: false
  num_workers: 1

schedules:
  use_threads: false
  num_workers: 1

code_servers:
  local_startup_timeout: 14400

python_logs:
  managed_python_loggers:
    - importing_worker