sensors:
  use_threads: false
  num_workers: 1

schedules:
  use_threads: false
  num_workers: 1

code_servers:
  local_startup_timeout: 3600

run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator
  config:
    max_concurrent_runs: 1